### ISSUE TITLE
Modals

### ISSUE THREAD

**Issue by RadekStrnad12** [keenthemes/ktui#6]
Hi, I have some issues with Modals.

1. Modal's setting "persistent" is not working, not even in preview.
2. Attribute "data-kt-modal-dismiss" is not working for me (although it is in preview). I cant make it work event in header nor footer.

Many thanks and cheers!
Radek

**Comment by sean0205** [comment]
Thanks for reporting this. The issue has been fixed and the preview redeployed(clear browser cache).

**Comment by RadekStrnad12** [comment]
Hi Sean, thank you for your response. 
I still have problem with modal dismissal. 

If I trigger modal with button, close buttons are working properly (with data-kt-modal-dismiss).
If I trigger modal with JavaScript (either when I create a new instance or getInstance) buttons are not working.

Can you please check it out?

Static backdrop is fine now, thanks.

**Comment by sean0205** [comment]
Hi,

Thank you for pointing this out! We'll review and address it. Your help in enhancing KtUI is greatly appreciated!

Best regards,
Sean

**Comment by RadekStrnad12** [comment]
Hi! 

Any progress with this issue? We are upgrading from Metronics 9.1 and different behavior of Modal element causes us trouble. :-)

Thanks!
Radek

**Comment by sean0205** [comment]
Hi,

Thank you for the heads-up.  We will try to ship this in the next week's planned update.

Regards,
Sean
